from tkinter import *
root= Tk()
root.geometry("400x300")
root.title("main")
def win():
    top= Toplevel()
    top.geometry("180x100")
    top.title("toplevel")
    l2= Label(top,text= "this is top level window")
    l2.pack()
    top.mainloop()
l= Label(root, text= "this is root window")
btn= Button(root,text= "click here to open another window",command=win)
l.pack()
btn.pack()
root.mainloop()    